name: Generate Snake Animation

# Define quando o workflow será executado
on:
  schedule:
    - cron: "0 0 * * *"  # Todos os dias à meia-noite
  push:
    branches:
      - main  # Executar também quando houver push na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_path: dist/snake.svg  # O caminho onde o SVG será salvo

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Generated snake animation"
          git push
